DROP TABLE dummy_entity;
DROP TABLE ROOT;
DROP TABLE INTERMEDIATE;
DROP TABLE LEAF;
DROP TABLE WITH_DELIMITED_COLUMN;

CREATE TABLE dummy_entity
(
    id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY
);

CREATE TABLE related_entity
(
    id           BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 ) PRIMARY KEYá
    content      VARCHAR(255),
    dummy_entity BIGINT
);
