CREATE TABLE related_entity
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255)
);

CREATE TABLE dummy_entity
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    related_entity_id BIGINT,
    FOREIGN KEY (related_entity_id) REFERENCES related_entity (id)
);
